<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = array(
            array(
                'name'=>'山隆通運',
                'img'=>'01.jpg',
                'type'=>'01',
                'url'=>'http://goyl.tw/demo'
            ),
            array(
                'name'=>'中興大學財金系',
                'img'=>'02.jpg',
                'type'=>'01',
                'url'=>'http://www.fin.nchu.edu.tw/',
            ),
            array(
                'name'=>'德盟儀器',
                'img'=>'03.jpg',
                'type'=>'01',
                'url'=>'http://www.adronic.com.tw/'
            ),
            array(
                'name'=>'德盟醫療',
                'img'=>'04.jpg',
                'type'=>'01',
                'url'=>'http://adronic-med.com.tw/'
            ),
            array(
                'name'=>'科隆',
                'img'=>'05.jpg',
                'type'=>'01',
                'url'=>'http://goty.tw/demo/'
            ),
            array(
                'name'=>'祐輝',
                'img'=>'06.jpg',
                'type'=>'01',
                'url'=>'http://goks.tw/'
            ),
            array(
                'name'=>'建鑫',
                'img'=>'07.jpg',
                'type'=>'01',
                'url'=>'http://www.chf-foundry.com/demo'
            ),
            array(
                'name'=>'煜益',
                'img'=>'08.jpg',
                'type'=>'01',
                'url'=>'http://www.yewee.com.tw/'
            ),
            array(
                'name'=>'建立',
                'img'=>'09.jpg',
                'type'=>'02',
                'url'=>''
            ),
            array(
                'name'=>'泰和碩',
                'img'=>'10.jpg',
                'type'=>'01',
                'url'=>'https://www.taxo.com.tw/'
            ),
            array(
                'name'=>'琮佑',
                'img'=>'11.jpg',
                'type'=>'01',
                'url'=>'http://tsongyo.com.tw/'
            ),
            array(
                'name'=>'精武道館',
                'img'=>'12.jpg',
                'type'=>'01',
                'url'=>'http://tcjwkarate.com/'
            ),
            array(
                'name'=>'樺正',
                'img'=>'13.jpg',
                'type'=>'01',
                'url'=>'http://jd-02.net/demo/'
            ),
            array(
                'name'=>'光神',
                'img'=>'14.jpg',
                'type'=>'02',
                'url'=>'https://www.digident.com.tw/'
            ),
            array(
                'name'=>'皇后',
                'img'=>'15.jpg',
                'type'=>'01',
                'url'=>'http://qic.tw/'
            ),
            array(
                'name'=>'瑞鎰',
                'img'=>'16.jpg',
                'type'=>'01',
                'url'=>'http://zayie.com.tw/'
            ),
            array(
                'name'=>'夏爾',
                'img'=>'17.jpg',
                'type'=>'01',
                'url'=>'http://charles.tw/'
            ),
            array(
                'name'=>'金高電',
                'img'=>'18.jpg',
                'type'=>'01',
                'url'=>'http://www.gigataiwan.com.tw/'
            ),
            array(
                'name'=>'巨葉',
                'img'=>'19.jpg',
                'type'=>'01',
                'url'=>'http://jungdesign.com.tw/'
            ),
            array(
                'name'=>'紐斯',
                'img'=>'20.jpg',
                'type'=>'01',
                'url'=>'http://forwardideatech.com/'
            ),
            array(
                'name'=>'產後照顧工會',
                'img'=>'21.jpg',
                'type'=>'01',
                'url'=>'http://www.pnc.org.tw/'
            ),
            array(
                'name'=>'益裕',
                'img'=>'22.jpg',
                'type'=>'01',
                'url'=>'http://www.yue.com.tw/'
            ),
            array(
                'name'=>'將門',
                'img'=>'23.jpg',
                'type'=>'01',
                'url'=>'http://www.jm-alonso.com/'
            ),
            array(
                'name'=>'貝聖多',
                'img'=>'24.jpg',
                'type'=>'01',
                'url'=>'http://bsdpostpartum.com.tw/'
            ),
            array(
                'name'=>'康鼎',
                'img'=>'25.jpg',
                'type'=>'01',
                'url'=>'http://www.kdtour.com.tw/'
            ),
            array(
                'name'=>'威森',
                'img'=>'26.jpg',
                'type'=>'01',
                'url'=>'https://www.aba-system.com/'
            ),
            array(
                'name'=>'楓林館',
                'img'=>'27.jpg',
                'type'=>'02',
                'url'=>''
            ),
        );
        $data = array(
            'items'=>$items,
        );
        return view('index',$data);
    }
}
